version: '2'

volumes:
  resin-data:

services:
  streamer:
    build: streamer
    volumes:
      - resin-data:/data
    ports:
      - 80:80/tcp
    privileged: 'true'
    labels:
      io.resin.update.strategy: 'kill-then-download'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
    restart: unless-stopped

  control:
    build: control
    devices:
      - /dev/serial0:/dev/serial0
    cap_add:
      - SYS_RAWIO
    labels:
      io.resin.update.strategy: 'kill-then-download'
    restart: unless-stopped
