FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:latest

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install pyroombaadapter gpiozero flask

COPY control.py /usr/local/src/control.py

ENV PYTHONUNBUFFERED=1

CMD ["python3", "/usr/local/src/control.py"]
